### ISSUE TITLE
Exception in thread "main" org.postgresql.util.PSQLException: FATAL: password authentication failed for user "root"

### ISSUE THREAD

**Issue by tstasevych** [bitcoinprivacy/Bitcoin-Graph-Explorer#45]
When trying to start BGE, getting password authentication error.
I configured username `postgres` with passowrd `trivial`. Do i need user root for DB? Which password it expects?

Thanks!

`bge start
Exception in thread "main" org.postgresql.util.PSQLException: FATAL: password authentication failed for user "root"
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:420)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:195)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:127)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
        at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:41)
        at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
        at org.postgresql.Driver.makeConnection(Driver.java:414)
        at org.postgresql.Driver.connect(Driver.java:282)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.createConnection(JdbcBackend.scala:70)
        at scala.slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:397)
        at scala.slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:397)
        at scala.slick.jdbc.JdbcBackend$BaseSession.metaData$lzycompute(JdbcBackend.scala:398)
        at scala.slick.jdbc.JdbcBackend$BaseSession.metaData(JdbcBackend.scala:398)
        at scala.slick.jdbc.meta.MTable$$anonfun$getTables$1.apply(MTable.scala:26)
        at scala.slick.jdbc.meta.MTable$$anonfun$getTables$1.apply(MTable.scala:26)
        at scala.slick.jdbc.ResultSetInvoker$$anon$3.createResultSet(ResultSetInvoker.scala:34)
        at scala.slick.jdbc.ResultSetInvoker.iteratorTo(ResultSetInvoker.scala:17)
        at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
        at scala.slick.jdbc.ResultSetInvoker.foreach(ResultSetInvoker.scala:12)
        at scala.slick.jdbc.Invoker$class.build(Invoker.scala:47)
        at scala.slick.jdbc.ResultSetInvoker.build(ResultSetInvoker.scala:12)
        at scala.slick.jdbc.Invoker$class.list(Invoker.scala:39)
        at scala.slick.jdbc.ResultSetInvoker.list(ResultSetInvoker.scala:12)
        at db.BitcoinDB$$anonfun$statsDone$1.apply(BitcoinDB.scala:33)
        at db.BitcoinDB$$anonfun$statsDone$1.apply(BitcoinDB.scala:32)
        at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
        at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
        at db.BitcoinDB$class.statsDone(BitcoinDB.scala:31)
        at Explorer$.statsDone(Explorer.scala:13)
        at Explorer$.delayedEndpoint$Explorer$1(Explorer.scala:17)
        at Explorer$delayedInit$body.apply(Explorer.scala:13)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at Explorer$.main(Explorer.scala:13)
        at Explorer.main(Explorer.scala)`

**Comment by tstasevych** [comment]
I created application.conf with username and password parameters and was able to connect to DB.

Thank you!
